<?php

/**
 * Implements hook_node_presave().
 */
function dcco_node_presave($node) {
  if($node->type == 'session') {
    $node->og_group_ref['und'][0]['target_id'] = 1;
  }
}
/**
 * Implements hook_cron().
 */
function dcco_cron() {
  // $product = commerce_product_new('cod_paid_event');
  //   $product->sku = 211;
  //   $product->title = 'DrupalCamp Colorado 2013';
  //   $product->status = 1;
  //   $product->uid = 1;
  //   $product->created = 1;
  //   $product->commerce_price[LANGUAGE_NONE][0]['amount'] = '1000';
  //   $product->commerce_price[LANGUAGE_NONE][0]['currency_code'] = 'USD';
  //   $product->field_registration[LANGUAGE_NONE][0]['registration_type'] = 'paid_event';

  //   commerce_product_save($product);
}

/**
 * Implements hook_user_presave().
 */
function dcco_user_presave(&$edit, $account, $category) {
  if (empty($account->og_user_node)) {
    $query = new EntityFieldQuery();
    $entities = $query->entityCondition('entity_type', 'node')
    ->propertyCondition('type', 'event')
    ->propertyCondition('title', 'DrupalCamp Colorado 2013')
    ->propertyCondition('status', 1)
    ->range(0,1)
    ->execute();
    if (!empty(

  $entities['node'])) {
      $node = node_load(array_shift(array_keys($entities['node'])));
    }
    $account->og_user_node['und'][0]['target_id'] = $node->nid;
  }
}
