<?php
/**
 * @file
 * cream_feature_schedule.features.taxonomy.inc
 */

/**
 * Implements hook_taxonomy_default_vocabularies().
 */
/*function cream_feature_schedule_taxonomy_default_vocabularies() {
  return array(
    'track' => array(
      'name' => 'Track',
      'machine_name' => 'track',
      'description' => '',
      'hierarchy' => 0,
      'module' => 'taxonomy',
      'weight' => 0,
      'rdf_mapping' => array(
        'rdftype' => array(
          0 => 'skos:ConceptScheme',
        ),
        'name' => array(
          'predicates' => array(
            0 => 'dc:title',
          ),
        ),
        'description' => array(
          'predicates' => array(
            0 => 'rdfs:comment',
          ),
        ),
      ),
    ),
  );
}*/
