<?php
/**
 * @file
 * Code for the DCCO Session Submission feature.
 */

include_once 'dcco_session_submission.features.inc';

/**
 * Implements hook_field_access().
 */
function dcco_session_submission_field_access($op, $field, $entity_type, $entity, $account) {
  $field_premission = !user_access('edit any session content', $account);
  if ($op == 'edit' && $field['field_name'] == 'field_accepted') {
    $field_premission = user_access('edit any session content', $account);
    if (!$field_premission) {
      return FALSE;
    }
  }
}
