<?php
/**
 * @file
 * Code for the CU_Slider feature.
 */

include_once 'cu_slider.features.inc';

/**
 * Implements hook_page_alter().
 */
function cu_slider_page_alter(&$page) {
  // Add cu slider css
  drupal_add_css(drupal_get_path('module', 'cu_slider') . '/cu_slider.css');
}

/**
 * Implements hook_theme_registry_alter().
 *
 * Let Drupal know that we've got bean--cu-slider.tpl.php in our module directory.
 */
function cu_slider_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'cu_slider');
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'bean', $module_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('bean');
  foreach ($hooks as $h) {
	  if (isset($theme_registry[$h]['theme paths'])) {
	    $first_element = array_shift($theme_registry[$h]['theme paths']);
	    array_unshift($theme_registry[$h]['theme paths'], array_shift($theme_registry[$h]['theme paths']), $module_path);
  	}
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Show examples of what the slider styles look like.
 */
function cu_slider_form_bean_form_alter(&$form, &$form_state, &$form_id) {
  if ($form['bean']['#value']->type == 'slider' || $form['bean']['#value']->type == 'homepage_slider') {
  	print_r("testees");
    $form['field_slider_style']['examples']['#markup'] = _cu_slider_examples();
  }
}

/**
 * Constructs the examples so it's easier to maintain 
 */
function _cu_slider_examples() {
  $path = base_path() . drupal_get_path('module', 'cu_slider') . '/examples/';
  $output = '<table cellspacing="0" cellpadding="10" border="0">
    <thead>
      <td colspan="2"><strong>' . t('Slider Style Examples') . '</strong></td>
    </thead>
    <tr>
      <th>Wide</th>
      <th>Wide with Teaser</th>
    </tr>
    <tr>
      <td><img src="' . $path . 'wide.jpg" alt="' . t('Wide') . '" /></td>
      <td><img src="' . $path . 'wideteaser.jpg" alt="' . t('Wide with Teaser') . '"  /></td>
    </tr>
    <tr>
      <th>Medium</th>
      <th>Small</th>
    </tr>
    <tr>
      <td><img src="' . $path . 'medium.jpg" alt="' . t('Medium') . '"  /></td>
      <td><img src="' . $path . 'small.jpg" alt="' . t('Small') . '"  /></td>
    </tr>
    </table><br />';
  return $output;
}

function cu_slider_update_7000() {
  module_enable('flexslider');
  module_enable('flexslider_views');
  module_enable('flexslider_views_slideshow');
}
